version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./tmp/mysqldb:/var/lib/mysql
  user-service:
    depends_on:
      - mysql
    image: user-service:0.1
    restart: on-failure
    ports:
      - '8000:8000'
    environment:
      SERVICE_PORT: 8000
      SPRING_APPLICATION_JSON: '{
        "server.servlet.context-path":  "/api",
        "api.exception.message": "Error",
        "spring.datasource.url"  : "jdbc:mysql://mysql:3306/testdb?useSSL=false",
        "spring.datasource.username" : "user",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL57Dialect",
        "spring.jpa.generate-ddl": true,
        "spring.jpa.hibernate.ddl-auto" : "create"
      }'
  event-service:
    depends_on:
      - user-service
    image: event-service:0.1
    restart: on-failure
    ports:
      - '8001:8001'
    environment:
      SERVICE_PORT: 8001
      SPRING_APPLICATION_JSON: '{
        "server.servlet.context-path":  "/api",
        "api.exception.message": "Error",
        "spring.datasource.url"  : "jdbc:mysql://mysql:3306/testdb?useSSL=false",
        "spring.datasource.username" : "user",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL57Dialect",
        "spring.jpa.generate-ddl": true,
        "spring.jpa.hibernate.ddl-auto": "create",
        "spring.mail.port": 587,
        "spring.mail.host": "smtp.gmail.com",
        "spring.mail.username": "user",
        "spring.mail.password": "pwd",
        "spring.mail.properties.mail.smtp.auth": true,
        "spring.mail.properties.mail.smtp.starttls.enable": true
      }'